# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
stages:
- stage: BuildTestStage
  displayName: 'Build and Test Stage'
  jobs:
    - job: PrepareBuild
      displayName: 'Buid and Test the product'
      steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
      - task: VSTest@2
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\bin\**\*test.dll
            **\bin\**\*tests.dll
          searchFolder: '$(System.DefaultWorkingDirectory)'
          codeCoverageEnabled: true
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
        env:
          AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
          AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
          AZURE_TENANT_ID:  $(AZURE_TENANT_ID)

    - job:
      displayName: 'Run the DevSecOps'
      dependsOn: PrepareBuild
      steps:
      - task: MicrosoftSecurityDevOps@1
        inputs:
          command: 'run'
          break: true
        condition: always()
- stage: DummyStage
  dependsOn: BuildTestStage
  displayName: DummyStage
  jobs:
  - job: 
    displayName: 'Dummy Job'
    steps:
      - task: CopyFiles@2
        displayName: 'Dummy Copy Task'
        name: dummyCopy
        inputs:
          SourceFolder: '$(agent.builddirectory)'
          Contents: '**'
          TargetFolder: '$(agent.builddirectory)/temp'
          CleanTargetFolder: true
          OverWrite: true
        condition: always()

      - script: echo "Step 1"
        displayName: 'Step 1'
        name: step1

      - script: echo "Step 2"
        displayName: 'Step 2'
        name: step2

      - script: echo "Step 3"
        displayName: 'Step 3'
        name: step3
  - job: 
    displayName: 'Another Dummy Job '
    steps:
      - script: echo "Step 1"
        displayName: 'Step 1'
        name: step1

      - script: echo "Step 2"
        displayName: 'Step 2'
        name: step2

      - script: echo "Step 3"
        displayName: 'Step 3'
        name: step3

- stage: MyDummyStage
  dependsOn: DummyStage
  displayName: MyDummyStage
  jobs:
  - job: MyDummyJobs
    displayName: 'My Dummy Job'
    steps:
      - task: CopyFiles@2
        displayName: 'Dummy Copy Task'
        name: dummyCopy
        inputs:
          SourceFolder: '$(agent.builddirectory)'
          Contents: '**'
          TargetFolder: '$(agent.builddirectory)/temp'
          CleanTargetFolder: true
          OverWrite: true
        condition: always()

      - script: echo "Step 1"
        displayName: 'Step 1'
        name: step1

      - script: echo "Step 2"
        displayName: 'Step 2'
        name: step2

      - script: echo "Step 3"
        displayName: 'Step 3'
        name: step3
  - job: MyAnotherDummyJobs
    dependsOn: MyDummyJobs
    displayName: 'Another Dummy Job '
    steps:
      - script: echo "Step 11"
        displayName: 'Step 11'
        name: step11

      - script: echo "Step 21"
        displayName: 'Step 21'
        name: step21

      - script: echo "Step 31"
        displayName: 'Step 31'
        name: step31
  - job: 
    dependsOn: MyAnotherDummyJobs
    displayName: 'Yet Another Dummy Job '
    steps:
      - script: echo "Step 12"
        displayName: 'Step 12'
        name: step12

      - script: echo "Step 22"
        displayName: 'Step 22'
        name: step22

      - script: echo "Step 33"
        displayName: 'Step 33'
        name: step33

- stage: YourDummyStage
  displayName: YourDummyStage
  dependsOn: BuildTestStage
  jobs:
  - job: YourDummyJobs
    displayName: 'Your Dummy Job'
    steps:
      - task: CopyFiles@2
        displayName: 'Your Dummy Copy Task'
        name: dummyCopy
        inputs:
          SourceFolder: '$(agent.builddirectory)'
          Contents: '**'
          TargetFolder: '$(agent.builddirectory)/temp'
          CleanTargetFolder: true
          OverWrite: true
        condition: always()

      - script: echo "Step 1"
        displayName: 'Step 1'
        name: step1

      - script: echo "Step 2"
        displayName: 'Step 2'
        name: step2

      - script: echo "Step 3"
        displayName: 'Step 3'
        name: step3
  - job: YourAnotherDummyJobs
    dependsOn: YourDummyJobs
    displayName: 'Another Your Dummy Job '
    steps:
      - script: echo "Step 11"
        displayName: 'Step 11'
        name: step11

      - script: echo "Step 21"
        displayName: 'Step 21'
        name: step21

      - script: echo "Step 31"
        displayName: 'Step 31'
        name: step31
  - job: 
    displayName: 'Yet Another Your Dummy Job '
    steps:
      - script: echo "Step 12"
        displayName: 'Step 12'
        name: step12

      - script: echo "Step 22"
        displayName: 'Step 22'
        name: step22

      - script: echo "Step 33"
        displayName: 'Step 33'
        name: step33
- stage: FinalStage
  displayName: FinalStage
  dependsOn: YourDummyStage
  jobs:
  - job: YourNEWDummyJobs
    displayName: 'Your NEW Dummy Job'
    steps:
    - script: echo "Step 11"
      displayName: 'Step 11'
      name: step11
  
  - job: YourNEWDummyJobs
    displayName: 'Your NEW Dummy Job'
    steps:
    - script: echo This script runs before the template's steps
    - template: ado/Stepsdummy.yml
    - script: echo This script runs before the template's steps

  - template: ado/Jobsdummy.yml

- template: ado/Stagedummy.yml 
